Update for beta 8
flarum/suspend pull request #12
Opened 2017-09-05 03:59 UTC by CDK2020

Sorry this one took me awhile, I was away from my computer.

2017-09-05 06:30 UTC, franzliedke requested changes

2017-09-05 06:30 UTC, franzliedke commented on src/Listener/AddClientAssets.php
>       * @param ConfigureClientView $event
Please remove the docblock.

2017-09-05 06:30 UTC, franzliedke commented on src/Listener/SaveSuspensionToDatabase.php
> +    public function whenSaving(Saving $event)
How about `whenSavingUser`?

2017-09-13 18:40 UTC, franzliedke commented
Ping @CDK2020. Can you take care of the requested changes here and in https://github.com/flarum/flarum-ext-akismet/pull/7? Otherwise I will do it, but I wanted to leave the chance to you. ;)

2017-09-13 18:47 UTC, CDK2020 commented
Sorry @franzliedke completely missed you message. I've fixed it, but styleCI is never happy

2017-09-13 19:41 UTC, franzliedke commented
@CDK2020 Great, thanks for the quick response. Can you also apply my suggestions here, in the flarum-ext-suspend PR?

2017-09-14 17:41 UTC, merged