WIP - Display suspension to user
flarum/suspend pull request #34
Opened 2021-02-18 18:25 UTC by imorland

Addresses https://github.com/flarum/core/issues/1447

- [x] Expand `SuspendUserModal` to include two new optional fields: reason (for moderator use) and message (for display to the suspended user
- [x] Display a modal to a suspended user, displaying the message entered by the moderator, and the length of the suspension
- [x] Move `Form-group` components to an `ItemList` for extensibility
- [ ] `compat` exports
- [ ] Expand notification blueprints to include email notifications of suspension/unsuspension, including the suspension message

2021-02-21 23:24 UTC, askvortsov1 commented
This is excellent, but will probably need to wait till the next release for review since we need to prioritize milestone items and fixed right now. Thanks for putting it together!

2021-03-16 21:21 UTC, davwheat commented on js/src/forum/components/SuspendUserModal.js
> +    this.attrs.user.save({ suspendedUntil: suspendedUntil, suspendReason: this.reason(), suspendMessage: this.message() }).then(
```suggestion
    this.attrs.user.save({ suspendedUntil, suspendReason: this.reason(), suspendMessage: this.message() }).then(
```

2021-03-16 21:25 UTC, davwheat commented on js/src/forum/components/SuspendUserModal.js
> +        ) : ''}
A little nicer than a ternary

```suggestion
        {this.status() === 'limited' && (
          <div className="SuspendUserModal-days-input">
            <input type="number"
              min="0"
              value={this.daysRemaining()}
              oninput={withAttr('value', this.daysRemaining)}
              className="FormControl" />
            {app.translator.trans('flarum-suspend.forum.suspend_user.limited_time_days_text')}
          </div>
        )}
```

2021-03-16 21:25 UTC, davwheat commented on locale/en.yml
>      # These translations are used in the suspension notifications
Just matches the existing standard of blank lines between sections
```suggestion
      title: This account is suspended

    # These translations are used in the suspension notifications
```

2021-03-16 21:25 UTC, davwheat commented on js/src/forum/components/SuspendUserModal.js
> +    let message = this.attrs.user.suspendMessage();
Can these be `const`s?

2021-03-16 21:29 UTC, davwheat commented on js/src/forum/components/SuspendUserModal.js
> +        ) : ''}
A little neater than a ternary :)
```suggestion
        {this.status() === 'limited' && (
          <div className="SuspendUserModal-days-input">
            <input type="number"
              min="0"
              value={this.daysRemaining()}
              oninput={withAttr('value', this.daysRemaining)}
              className="FormControl" />
            {app.translator.trans('flarum-suspend.forum.suspend_user.limited_time_days_text')}
          </div>
        )}
```

2021-03-16 22:21 UTC, askvortsov1 requested changes

2021-03-16 22:21 UTC, askvortsov1 commented on js/src/forum/components/SuspendUserModal.js
>      if (new Date() > until) until = null;
Could this be a ternary?

2021-03-16 22:21 UTC, askvortsov1 commented on locale/en.yml
> +      subject: You have been suspended
"Your account has been suspended"?

2021-03-16 22:21 UTC, askvortsov1 commented on locale/en.yml
> +        You've been suspended for the following reason:
Should include a bit more context: "suspended from ______", maybe a duration?

2021-04-27 15:16 UTC, datitisev commented
This PR now includes commits that aren't relevant to the issue it's trying to fix.

2021-05-04 14:32 UTC, davwheat commented
It might be worth copying the gg branch to this repo, then recreating the PR so we could actually merge this.

2021-10-25 17:36 UTC, askvortsov1 commented
@imorland is this something you're still interested in working on? If not, we might want to close this for now

2021-10-27 22:14 UTC, imorland commented
@askvortsov1 I'd absolutely like to get this completed. Unfortunately this was started during my time at giffgaff, so I'm not able to make any changes to this PR now.

As @davwheat suggests, I'd vote for almost "starting again" with this one

2021-10-27 22:15 UTC, askvortsov1 commented
Alright, I'll close this one for now then.

2021-10-27 22:15 UTC, closed without merging